### PR TITLE
new

### PR DESCRIPTION
**Pull request by HDembinski**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by HDembinski** [comment]
@conda-forge-admin, please rerender

**Comment by chrisburr** [comment]
@HDembinski You need to use forks when updating conda-forge packages as builds on all branches are deployed. (To allow packages like Python/Clang/... to maintain multiple releases on different branches)

**Comment by HDembinski** [comment]
Ok, next time I will take that warning seriously. Maybe.

**Comment by HDembinski** [comment]
It was taking too long ;)

**Pull request merged**
