### PR TITLE
feat: Enable SIMD optimizations

### PR DESCRIPTION
**Pull request by matthewfeickert**
* Add x86_64-microarch-level as a 'build' requirement.
   - microarch_level 4 not supported yet so only add level 1 to 3.
   - c.f. https://github.com/conda-forge/microarch-level-feedstock/issues/5
* Set the build number based on the microarch_level.
* Add conda_build_config.yaml with microarch_level.
* c.f. https://prefix.dev/blog/building_cpu_optimized_packages
* Bump build number.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [N/A] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@conda-forge-admin, please rerender

**Comment by matthewfeickert** [comment]
@conda-forge/iminuit this is ready for review. Let me know if you have any questions. 👍

**Comment by henryiii** [comment]
Do you know if PR's are actually making anything faster? Some code bases can effectively use vector instructions and get a nice 2x+ speed up and some don't see much benefit.

**Comment by matthewfeickert** [comment]
> Do you know if PR's are actually making anything faster? Some code bases can effectively use vector instructions and get a nice 2x+ speed up and some don't see much benefit.

@henryiii Good question. I don't have any explict checks to show at the moment. I'll defer to you if you think this is worth doing here (and for the other ones that I've opened up), and if so I'll do some custom builds and test comparisons when I'm back from work travel in a few weeks.

**Comment by matthewfeickert** [comment]
Placed into draft given that needs to be rebased following PR #108 and needs https://github.com/conda-forge/microarch-level-feedstock/issues/10 to be resolved before can be merged.

**Review by HDembinski — APPROVED** [review]
I cannot review this, but I appreciate the effort and I think it sound all good.

**Comment by HDembinski** [comment]
That being said, iminuit will not profit from such optimizations, because the minimizing algorithm is typically not the bottleneck, it is the calculation of the cost function, which ideally should be JIT-compiled for the specific architecture.

**Comment by matthewfeickert** [comment]
> That being said, iminuit will not profit from such optimizations, because the minimizing algorithm is typically not the bottleneck

Sounds good. No need to add more build complexity if it won't help, so closing this. :+1: Thanks, Hans, for the info!

**Pull request closed without merging**
