### PR TITLE
ENH rebuild and specify compilers

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes #11

### CODE REVIEW

**Comment by beckermr** [comment]
Weird docker failure killed the build and circle won't let me restart the build via the UI. Hence the extra commit.

**Comment by beckermr** [comment]
lol the internet is broken

**Comment by beckermr** [comment]
@conda-forge-admin, please update circle

**Comment by beckermr** [comment]
@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge/iminuit I went ahead a finished the rebuild of this feedstock. This PR is ready to merge!

**Comment by HDembinski** [comment]
@beckermr Thank you for the update!

**Pull request merged**
