### PR TITLE
Fixing build on ARM OSx. Updating to v2.8.2

### PR DESCRIPTION
**Pull request by tdegeus**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
@chrisburr @henryiii @beckermr I was having trouble with the singing issue in https://github.com/conda-forge/iminuit-feedstock/pull/58, https://github.com/conda-forge/iminuit-feedstock/pull/60, https://github.com/conda-forge/iminuit-feedstock/pull/61 as well. I finally realised that `CMAKE_ARGS` was not passed, which is required for cross-compilation here. The CI is now all green (note that there is some bug so that the Azure runs are not shown here; they can be found [manually](https://dev.azure.com/conda-forge/feedstock-builds/_build)).

For my own packages I'm still stuck with an issue...
The only difference is that I am using `FindPython.cmake` on the the (deprecated) FindPythonLibs.cmake that is used here (see [docs](https://conda-forge.org/docs/maintainer/knowledge_base.html#using-cmake)), because I want to also find the NumPy headers. The issue that I am having is that somehow `FindPython.cmake` is not able to find the Python installation. See https://github.com/conda-forge/qpot-feedstock/pull/31 (see the issue with Azure not show above).

So I'm hoping that now that I fixed your issue, you can help me with mine ;)

**Comment by henryiii** [comment]
Fantastic, thanks! If this isn't in `pybind/cmake_example`, it should be added. Though (hopefully, as of 0.12) we are about at the point that scikit-build can handle anything that cmake_example does - manually maintaining this for each and every CMake-setuptools package is a pain. This also should be added to upstream, I can make a PR later.

**Comment by henryiii** [comment]
@tdegeus One thing you could/should do (that scikit-build does) is pass through the `sys.executable` to `PYTHON_EXECUTABLE` (FindPythonLibs) or `Python_EXECUTABLE` (FindPython). Scikit-build doesn't do the FindPython one yet (though you can easily set one to the other in your CMakeLists), I'm planning on refactoring the argument passing in the near future for Scikit-build to hide unused variable warnings, which will make it easier to pass this through.

**Comment by tdegeus** [comment]
Thanks @henryiii . 

> Fantastic, thanks! If this isn't in `pybind/cmake_example`, it should be added. Though (hopefully, as of 0.12) we are about at the point that scikit-build can handle anything that cmake_example does - manually maintaining this for each and every CMake-setuptools package is a pain. This also should be added to upstream, I can make a PR later.

I already opened an issue https://github.com/pybind/cmake_example/issues/52 , though at that time I too did not so clearly recognise the significance. 

Great news about scikit-build, can't wait to switch! What is be the approximate release date of 0.12?

> @tdegeus One thing you could/should do (that scikit-build does) is pass through the `sys.executable` to `PYTHON_EXECUTABLE` (FindPythonLibs) or `Python_EXECUTABLE` (FindPython). Scikit-build doesn't do the FindPython one yet (though you can easily set one to the other in your CMakeLists), I'm planning on refactoring the argument passing in the near future for Scikit-build to hide unused variable warnings, which will make it easier to pass this through.

I'm already passing though `sys.executable`. In fact, I'm simply using https://github.com/pybind/cmake_example with as only difference that I am using `-DPython_EXECUTABLE` (and the 'famous' `CMAKE_ARGS` environment variable). So unfortunately my issue on conda-forge ARM OSx is a bit more persistent...

**Comment by henryiii** [comment]
0.12 came out a few days ago, supporting Apple Silicon and MSVC 2019. Next we'll probably work on some of these points, including the pass-through work.

**Comment by tdegeus** [comment]
I failed to notice, I guess because https://github.com/conda-forge/scikit-build-feedstock/pull/46 is blocked. Not sure how difficult it is to unblock?

**Comment by henryiii** [comment]
Thanks!! Sorry, I was waiting for scikit-hep/iminuit#683 to go in, then forgot about this.

**Pull request merged**
