### PR TITLE
DO NOT MERGE: Debugging code signing issue

### PR DESCRIPTION
**Pull request by chrisburr**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tdegeus** [comment]
Should the feedstock be rerendered or do we wait what happens here?

**Comment by chrisburr** [comment]
> Should the feedstock be rerendered or do we wait what happens here?

I was going to suggest trying the first build without and then rerendering to isolate if it's a conda-smithy issue or a issue with the runner+installed software.

Looks like while typing it's already failed so it's something unrelated to conda-smithy.

**Comment by tdegeus** [comment]
Indeed!

**Comment by tdegeus** [comment]
Note that compare to this library that uses `cmake ....` I tried adding `cmake ${CMAKE_ARGS} ....` in  https://github.com/conda-forge/gmattensor-feedstock/pull/13 without effect on the error

**Comment by beckermr** [comment]
@xhochy @erykoff @isuruf we have an osx-arm signing issue....

**Comment by tdegeus** [comment]
To have a trace, thanks to @isuruf ([comment on gitter](https://gitter.im/conda-forge/conda-forge.github.io)) this can be solved by setting
```yaml
c_compiler_version:  # [osx]
- 12  # [osx]
cxx_compiler_version:  # [osx]
- 12  # [osx]
```
in `conda_build_config.yaml`. I leave it up to the others to comment if this will become the default (soon)

**Comment by tdegeus** [comment]
Some debugging later I can now say that there is no signing error, the problem is simply that `CMAKE_ARGS` is not passed : https://github.com/conda-forge/iminuit-feedstock/pull/62 .

Now that this is fixed, there is still some help wanted for other packages ;), see https://github.com/conda-forge/iminuit-feedstock/pull/62

**Pull request closed without merging**
